### ISSUE TITLE
Incorrectly formatting > as &gt;

### ISSUE THREAD

**Issue by cardin** [Exirel/pylint-json2html#6] opened 2020-04-16 04:49 UTC
I ran the simple command:
```cmd
pylint .\facenet-master\align --output-format=json | pylint-json2html -o pylint.html
```
Then the extended command:
```cmd
pylint .\facenet-master\align --load-plugins=pylint_json2html --output-format=jsonextended | pylint-json2html -f jsonextended -o pylint_extended.html
```

I noticed that the simple command gave output that was this:

372 | 30 | convention | bad-whitespace | C0326 |   | ```Exactly one space required around comparison         ipass = np.where(score&gt;threshold[1])                               ^```
-- | -- | -- | -- | -- | -- | --

Compared to the extended command:

372 | 30 | convention | bad-whitespace | C0326 |   |``` Exactly one space required around comparison         ipass = np.where(score>threshold[1])                               ^```
-- | -- | -- | -- | -- | -- | --

Basically, the > symbol is not being correctly escaped.

Environment:
* Windows 10
* Python 3.7.0
* Pylint 2.4.4
* Pylint-json2html 0.2.0

**Comment by Exirel** [comment] 2021-03-16 23:46
Hi, sorry for not responding here for so long (2020, you know, stuff happening).

That's weird, the template doesn't change based on the input. Could you provide the JSON output from Pylint?

**Comment by Exirel** [comment] 2021-03-17 18:07
I generated a json file by creating a fake file with `<` but couldn't generate the same error (bad-whitespace), so I'm not sure this is fixed or not.

However, I cannot reproduce that with my current version of pylint, so I'll say: won't fix.

**Closed as completed by Exirel** 2021-03-17 18:07 UTC
Labels: invalid, question
