### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by khashashin** [Exirel/pylint-json2html#9] opened 2021-03-15 00:04 UTC
Running in to error on Windows 10. The error:

```
(server) H:\GitHub\project\project_mott\server>python manage.py pylint | pylint-json2html -o pylint.html
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "H:\GitHub\project\project_mott\server\.venv\Scripts\pylint-json2html.exe\__main__.py", line 7, in <module>
  File "h:\github\project\project_mott\server\.venv\lib\site-packages\pylint_json2html\__init__.py", line 278, in main
    print(report.render(), file=options.output)
  File "C:\Python39\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u04c0' in position 93329: character maps to <undefined>
```

**Comment by Exirel** [comment] 2021-03-16 23:44
Hm. That's weird. As far as I remember, this tools assume everything is utf-8, but I see that it tries to use the Windows default encoding (cp1251). I don't have a Windows to try this on, and I'm not keen on dealing with Windows for that project.

Maybe you could send me the result of pylint and I can see if I can reproduce anyway.

**Comment by khashashin** [comment] 2021-03-17 14:14
Sure: https://github.com/khashashin/maciev_dict_parser/blob/master/pylint_report.json

Note: it is just one of my public repository and the code in it not related to the json file.

Btw. the character that pylint-json2html tried to decode `'\u04c0'` was this one: https://en.wikipedia.org/wiki/Palochka

**Comment by Exirel** [comment] 2021-03-17 15:49
I couldn't reproduce the bug. However, I think it has something to do with the encoding of your system, that somehow messes with how the result is printed out (using the `print` function, that is).

For instance, I was able to copy the content into a file, and I was able to generate that:

![image](https://user-images.githubusercontent.com/3259552/111496422-986eff80-8740-11eb-9369-71bfc9d806d2.png)

Since I can't reproduce exactly (all my system are in UTF-8, and I'm not really sure what will fix the actual problem), ~~I'll add 2 new options:~~ **EDIT** here is my thought process and what I might do:

* JSON file are supposed to be encoded as UTF-8 (and it's not the problem you are having anyway)
* I'll add an option to select the encoding for output file, but that won't work for stdout that is always opened with mode "w", and not "wb"

And I hope that this will help solving the issue for you.

Side note: I also saw that the rendering of message doesn't keep break-lines, and that's not pretty, so I'll fix that too.

**Comment by Exirel** [comment] 2021-03-17 17:55
Ok, that should be fixed in 0.3.0 (to be release very soon), by using the option `-e utf-8` to ensure that the output is encoded as UTF-8. And also I replaced my very old `print(...)` by `file.write(...)`.

**Closed as completed by Exirel** 2021-03-17 17:55 UTC
Labels: bug

**Comment by khashashin** [comment] 2021-03-17 19:33
Thank you very much for the quick fix

**Comment by khashashin** [comment] 2021-03-17 19:41
Ok it works now, even without `-e utf-8` option.

**Comment by Exirel** [comment] 2021-03-17 23:22
Awesome!
